sudo: required
dist: trusty

language: node_js

node_js:
  - 7.5

addons:
  ssh_known_hosts: artemis.garcon.ovh

install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key
    add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable
    main" >> /etc/apt/sources.list.d/google-chrome.list'
  - sudo apt-get update -q
  - sudo apt-get install -q google-chrome-stable

before_script:
  - npm install

script:
  - ng build -prod

before_deploy:
  - openssl aes-256-cbc -K $encrypted_6b738f490133_key -iv $encrypted_6b738f490133_iv -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist begarco@artemis.garcon.ovh:/srv/garcon
  on:
    branch: master
